services:
  api:
    build:
      context: ../../..
      dockerfile: apps/back/api/Dockerfile.dev
    container_name: api
    ports:
      - "${API_PORT:-4000}:4000"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Seoul
    env_file:
      - ../../../../.env
    volumes:
      - ./src:/app/apps/back/api/src
      - libs_data:/app/libs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
