include:
  - path: front/docker-compose.dev.yml
    project_directory: ./front
  - path: infra/docker-compose.dev.yml
    project_directory: ./infra
  - path: back/docker-compose.dev.yml
    project_directory: ./back

networks:
  app-network:
    driver: bridge
