services:
  mobile:
    build:
      context: ../../..
      dockerfile: apps/front/mobile/Dockerfile.dev
    container_name: mobile
    ports:
      - "${MOBILE_PORT:-8081}:8081"
      - "19000:19000"
      - "19001:19001"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Seoul
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    env_file:
      - ../../../../.env
    volumes:
      - ./src:/app/apps/front/mobile/src
      - libs_data:/app/libs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge